Chris search alpha
clockwise-software/platinum pull request #2
Opened 2021-03-31 08:09 UTC by cgrillo-bit

I wrote a new search page. I am having trouble linking Boostrap 4 and my styles.css I wrote.

2021-03-31 17:53 UTC, jarulsamy commented
Looking good so far!

I think the inclusion of bootstrap and other frameworks should include the integrity checks:
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>SE Bootcamp</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

     <!-- Rest of generalPageStyle.html -->
```

I see that you wanted help on getting CSS to work correctly on `EmployeeSearch.html`, but as far as I can tell it is correctly linking to bootstrap? The page does have CSS loaded, although it doesn't look quite like the demo you sent in slack. Let me know if I misunderstood.

2021-04-02 16:26 UTC, rafecoolz requested changes
Looking pretty good! I noticed that the "Add Employee" on the search page isn't going there so I requested that as a small change but otherwise its looking really good.

2021-04-02 16:26 UTC, rafecoolz commented on src/templates/EmployeeSearch.html
> +         <input type="submit" name="" value="Add Employee" /><br />
Can you make it so this is a button and will route to the "Add Employee" page?

2021-04-03 21:26 UTC, jarulsamy approved these changes

2021-04-03 21:33 UTC, merged